apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ni5liqf8f-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ni5liqf8f-java-springboot-gitops